export const nodeTemplates = [
  {
    id: 'frontend',
    title: 'Frontend',
    type: 'frontend',
    width: 160,
    height: 80,
    color: '#185FA5',
    bgColor: '#E6F1FB',
    icon: '⬡',
    description: 'UI layer / client',
  },
  {
    id: 'backend',
    title: 'Backend',
    type: 'backend',
    width: 160,
    height: 80,
    color: '#27500A',
    bgColor: '#EAF3DE',
    icon: '⚙',
    description: 'API / server logic',
  },
  {
    id: 'database',
    title: 'Database',
    type: 'database',
    width: 160,
    height: 80,
    color: '#633806',
    bgColor: '#FAEEDA',
    icon: '⬡',
    description: 'Data storage layer',
  },
  {
    id: 'service',
    title: 'Service',
    type: 'service',
    width: 160,
    height: 80,
    color: '#26215C',
    bgColor: '#EEEDFE',
    icon: '◈',
    description: 'Microservice / worker',
  },
  {
    id: 'jwt',
    title: 'JWT Generator',
    type: 'jwt',
    width: 160,
    height: 80,
    color: '#5C4A00',
    bgColor: '#FFF9C4',
    icon: '⚿',
    description: 'Auth token service',
  },
  {
    id: 'queue',
    title: 'Message Queue',
    type: 'queue',
    width: 160,
    height: 80,
    color: '#993C1D',
    bgColor: '#FAECE7',
    icon: '≡',
    description: 'Event / message bus',
  },
  {
    id: 'cache',
    title: 'Cache',
    type: 'cache',
    width: 160,
    height: 80,
    color: '#0F6E56',
    bgColor: '#E1F5EE',
    icon: '⚡',
    description: 'Redis / in-memory cache',
  },
  {
    id: 'gateway',
    title: 'API Gateway',
    type: 'gateway',
    width: 160,
    height: 80,
    color: '#1a6b3c',
    bgColor: '#E1F5EE',
    icon: '⇄',
    description: 'Entry point / proxy',
  },
  {
    id: 'note',
    title: 'Note',
    type: 'note',
    width: 140,
    height: 70,
    color: '#000000',
    bgColor: '#FFF9C4',
    icon: '📝',
    description: 'Add an annotative note',
  },
];

export const getTemplateStyle = (type) => {
  const t = nodeTemplates.find(n => n.type === type);
  return t ? { color: t.color, bgColor: t.bgColor } : { color: '#6b6965', bgColor: '#f0efee' };
};